telegram_token: "tg_token_here"
# ONLY IF YOU USING TEMPLATE required for test

template_path: ""
time_zone: "Europe/Kiev"
split_token: "|"

# ONLY IF YOU USING DATA FORMATTING FUNCTION, NOTE for developer: important or test fail
time_outdata: "02-01-2006 15:04:05"
